### ISSUE TITLE
Update file vi_VN.lang

### ISSUE THREAD

**Issue by 4555uuuu** [LiteLDev-LXL/iLand-Core#4]
[vi_VN.zip](https://github.com/LiteLDev-LXL/iLand-Core/files/7072837/vi_VN.zip)

**Comment by TungstenVn** [comment]
please create a pull request, not like this

**Comment by Redbeanw44602** [comment]
Please use the pull&request function, thank you for your contribution.

Put the language files in the `3rd-languages` folder. 
I will launch the ability to install language packs in the near future.
